# Generated by Django 5.2.6 on 2025-10-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('new', 'New'), ('progress', 'In Progress'), ('ready', 'Ready'), ('failed', 'Failed'), ('forbidden', 'Forbidden')], default='new', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('file_partial', models.FileField(blank=True, upload_to='partial/')),
                ('file_completed', models.FileField(blank=True, upload_to='completed/')),
                ('size_partial', models.BigIntegerField(default=0)),
                ('size_completed', models.BigIntegerField(default=0)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_ready', models.DateTimeField(null=True)),
                ('datetime_failed', models.DateTimeField(null=True)),
            ],
        ),
    ]
